# Numpy

In [1]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [2]:
a[0]

1

In [3]:
#size of one array
a.itemsize

8

In [4]:
a.size

3

In [5]:
a = np.array([1, 2, 3], dtype = np.float64)
a.itemsize

8

In [6]:
a = np.array([1, 2, 3], dtype = np.complex128)
a.itemsize

16

In [7]:
a.ndim

1

In [8]:
a = np.array([[1, 2],[3, 4],[5, 6]])
a.ndim

2

In [9]:
a.dtype

dtype('int64')

In [10]:
a.shape

(3, 2)

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype = complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
print("A\n", np.arange(4).reshape(2, 2), "\n")
print("A\n", np.arange(4, 10), "\n")
print("A\n", np.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [15]:
a=np.arange(4).reshape(2, 2)
print(a.ravel())
print(a)

[0 1 2 3]
[[0 1]
 [2 3]]


In [16]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis = 0)) # sum of columns
print(a.sum(axis = 1)) # sum of rows

1
6
21
[ 9 12]
[ 3  7 11]


In [17]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [18]:
np.std(a)

1.707825127659933

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Sum of matrices : ")
print(a + b)
print("Substraction of matrices : ")
print(a - b)
print("Multiplication : ")
print(a * b)
print("Division : ")
print(a/b)
print("Dot product")
print(a.dot(b))

Sum of matrices : 
[[ 6  8]
 [10 12]]
Substraction of matrices : 
[[-4 -4]
 [-4 -4]]
Multiplication : 
[[ 5 12]
 [21 32]]
Division : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Dot product
[[19 22]
 [43 50]]


In [20]:
a = np.array([6, 7, 8])
print(a[0 : 2])
print(a[-1])

a= np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
print(a[1, 2])
print(a[-1, 0:2])


[6 7]
8
3
[9 3]


In [21]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [22]:
a= np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [23]:
for row in a:
    for cell in row:
        print(cell)

6
7
8
1
2
3
9
3
2


In [24]:
a = np.arange(12).reshape(3, 4)
print(a)

b = a > 4
print(b)

print(a[b])

# replcae all the numbers with a certain number
a[b] = -1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [25]:
a = np.arange(12).reshape(3, 4)
# going row by row print each of the program
for x in np.nditer(a, order = 'C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [26]:
for x in np.nditer(a, order = 'F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [27]:
#print entire column in Fortan order
for x in np.nditer(a, order = 'F', flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [28]:
# modify the elements while iterating through the array
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [29]:
#iterate through two numpy arrays simultaneously
b = np.arange(3, 15, 4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

In [30]:
for (x, y) in np.nditer([a, b]):
    print(x, y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [31]:
b = np.arange(3, 19, 5).reshape(4, 1)
for (x, y) in np.nditer([a, b]):
    print(x, y)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [32]:
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([[6, 7], [8, 9], [10, 11]])
print(a)
print(b)
np.vstack((a, b))
np.hstack((a, b))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [33]:
a = np.arange(30).reshape(2, 15)
result = np.hsplit(a, 3)
print("Horizontal split")
print(result[0])
print(result[1])
print(result[2])
print("Vertical split")
result = np.vsplit(a, 2)
print(result[0])
print(result[1])


Horizontal split
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]
Vertical split
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [34]:
#Multinested array
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [6, 7, 8, 9, 1]
my_lst3 = [5, 4, 3, 6, 7]
arr = np.array([my_lst1, my_lst2, my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [5, 4, 3, 6, 7]])

In [35]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [36]:
#copy function and broadcasting
arr=np.arange(1, 10)
print(arr)
arr[3:]=100
print(arr)

[1 2 3 4 5 6 7 8 9]
[  1   2   3 100 100 100 100 100 100]


In [37]:
arr1 = arr
arr1[3:] = 500
print(arr)
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [38]:
arr=np.arange(1, 10)
print(arr)
arr1 = arr.copy()
arr1[3:] = 1000
print(arr1)
print(arr)

[1 2 3 4 5 6 7 8 9]
[   1    2    3 1000 1000 1000 1000 1000 1000]
[1 2 3 4 5 6 7 8 9]


In [39]:
print(np.random.rand(3, 3))
np.random.randn(4, 4)

[[0.9337959  0.35894772 0.54048541]
 [0.77198904 0.33204467 0.92774912]
 [0.07884867 0.73548385 0.24817412]]


array([[ 0.0943822 , -2.27825032,  1.39911273,  0.0865502 ],
       [-0.42947973,  0.67875569,  0.62427925, -0.1966978 ],
       [ 1.15728203, -0.10375212,  0.88777261,  1.04081924],
       [-0.98531827,  0.24243362, -0.18657348, -1.72927421]])

In [40]:
x = np.array([[[1],[2]],[[3],[4]]])

In [41]:
x.shape

(2, 2, 1)

In [42]:
x = np.array([1, 2])

In [43]:
x.shape

(2,)

In [44]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [45]:
x = np.array([[1,2],[3,4]])
#np.repeat(x, 2)

In [46]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [49]:
print(np.linalg.norm(-3.14))

3.14


In [50]:
print(abs(-3.14))

3.14
